### ISSUE TITLE
Install Instructions, error on step 3

### ISSUE THREAD

**Issue by wrathagom** [ShubhankarS/duckling-rest#1]
I have never used Clojure before today and was looking for an easy way to use duckling in a project I am working on. So thanks for making it so easy! When I cloned this project and tried to follow you're instructions I was getting the below error on step 3:

`Could not find artifact wit:duckling:jar:1.0.85-SNAPSHOT in clojars (https://clojars.org/repo/)
This could be due to a typo in :dependencies or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.`

Knowing that I had just done something in the duckling directory I searched around and found the suggestion to do the below from this SO http://stackoverflow.com/questions/2404426/leiningen-how-to-add-dependencies-for-local-jars

`lein pom; lein jar; lein install`

I did this in the duckling directory, essentially replacing step 2. Then everything worked normally.

**Comment by ShubhankarS** [comment]
Thanks for pointing it out. Have added some more instructions to the [README file](https://github.com/ShubhankarS/duckling-rest/blob/master/README.md). That should make things clear

**Comment by wrathagom** [comment]
No, thank you for wrapping this up so I didn't have to dive into it too much.

Thanks again.
